Update README.org
joonro/ConEmu-Color-Themes pull request #10
Opened 2017-02-19 13:02 UTC by dhruvdutt

2017-02-20 22:48 UTC, shiitake requested changes
Palette is not spelled correctly.

2017-02-20 22:48 UTC, shiitake commented on README.org
> +   custom color palette already, it should be =Pallete2= for the new one:
This should be spelled **Palette** (one L, two T's)

2017-02-21 07:47 UTC, dhruvdutt commented
Updated.

2017-02-21 14:14 UTC, shiitake approved these changes

2017-03-03 17:10 UTC, merged

2017-03-03 17:10 UTC, joonro commented
Thanks a lot! I changed the base branch into `develop` and merged the PR.