add material darker theme
joonro/ConEmu-Color-Themes pull request #9
Opened 2017-02-17 21:16 UTC by chantisnake

2017-02-21 14:22 UTC, shiitake requested changes
I'm really excited to try this theme out! It looks very cool.   :)

Please see a few of the recommended changes and let me know if you have any questions.

2017-02-21 14:22 UTC, shiitake commented on material-darker.xml
> +		<key name=".Vanilla" modified="2017-02-15 13:30:28" build="160724">
Instead of .Vanilla the name value should be Palette1

2017-02-21 14:22 UTC, shiitake commented on material-darker.xml
> +			<value name="ColorTable00" type="dword" data="00151515"/>
It looks like the theme is missing several common elements. 

Particularly Name, ExtendedColors, ExtendColorIdx, TextColorIdx, BackColorIdx, PopTextColorIdx, PopBackColorIdx. 

You might compare this to another one of the themes to verify - [moe-dark](https://github.com/joonro/ConEmu-Color-Themes/blob/master/moe-dark.xml)

2017-02-21 14:24 UTC, shiitake commented on material-darker.xml
> +			<value name="ColorTable31" type="dword" data="00ffffff"/>
It looks like the theme is missing several common elements.

Particularly Name, ExtendedColors, ExtendColorIdx, TextColorIdx, BackColorIdx, PopTextColorIdx, PopBackColorIdx.

You might compare this to another one of the themes to verify - moe-dark

2017-02-21 21:18 UTC, chantisnake commented
thank you, I will have it fixed soon

2017-04-16 07:27 UTC, merged

2017-04-16 08:02 UTC, joonro commented
Hi - I merged your changes and completed the update of the repo - please see `material-sublime-darker` for your color theme.

2017-04-16 10:54 UTC, chantisnake commented
Thank you. 

Sorry this has been so long, I almost forget about this pr.

Thank you again